# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadSecureFile@1
  name: ssh_private_key
  inputs:
    secureFile: secure_file_1

- script: |
    cp $(ssh_private_key.secureFilePath) .
    
- bash : |
    echo $(ssh_private_key.secureFilePath)
    cat $(ssh_private_key.secureFilePath)
    PRIVATE_KEY=`cat $(ssh_private_key.secureFilePath)`
    echo $(PRIVATE_KEY)
    echo $PRIVATE_KEY
    echo "##vso[task.setvariable variable=PRIVATE_KEY]$PRIVATE_KEY"
    echo $(PRIVATE_KEY)
    echo $PRIVATE_KEY

- task: Docker@2
  displayName: verify ssh key
  inputs:
    repository: '$(Build.DefinitionName)'
    command: 'build'
    Dockerfile: 'DockerFile'
    buildContext: '.'
    tags: '$(Build.BuildId)-$(Build.SourceVersion)'
    arguments: '--build-arg "BRANCH=$(PRIVATE_KEY)"'



