FROM ubuntu:18.04 as ubuntu

#arguments
ARG BRANCH

RUN pwd

RUN ls 


RUN mkdir $HOME/ssh_file

# Copy Private Key Over
COPY secure_file_1 ./
RUN mv  ./secure_file_1 $HOME/ssh_file

RUN cat $HOME/ssh_file/secure_file_1

RUN ls $HOME/ssh_file

FROM golang:1.15.3-alpine3.12 as go1.15

RUN mkdir $GOPATH/ssh_file

WORKDIR $GOPATH/ssh_file/

COPY --from=ubuntu $HOME/ssh_file .

RUN pwd

RUN ls

RUN cat secure_file_1
