from ubuntu:18.04

#arguments
ARG BRANCH

RUN echo "$BRANCH"

RUN mkdir ~/.ssh

RUN echo -e "$BRANCH" > $HOME/.ssh/id_rsa

RUN cat ~/.ssh/id_rsa

FROM golang:1.15.3-alpine3.12 

WORKDIR /

COPY $BRANCH ./

RUN cat ./secure_file_1

