FROM ubuntu:18.04 as ubuntu

#arguments
ARG BRANCH

RUN pwd

RUN ls 

# Copy Private Key Over
COPY secure_file_1 $HOME/

RUN cat $HOME/secure_file_1

FROM golang:1.15.3-alpine3.12 as go1.15

COPY --from=ubuntu $HOME/ $GOPATH/

RUN ls $GOPATH
